# Run: pre-commit install && pre-commit run --all-files
repos:
  # --- Python: Ruff (lint + format) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        name: ruff (lint)
        args: [--fix]
        additional_dependencies: []   # pin extras if needed
        files: ^backend/
      - id: ruff-format
        name: ruff (format)
        files: ^backend/

  # --- Basic hygiene for all files ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  # --- Frontend: Prettier (JS/TS/CSS/MD/etc.) ---
  - repo: https://github.com/kaechele/pre-commit-mirror-prettier
    rev: v3.6.2   # or pin the exact version you want
    hooks:
      - id: prettier
        files: ^frontend/
        # additional_dependencies: []  # add plugins later if needed
