
version: "3.9"

services:
  db:
    image: postgres:16

    env_file:
      - ../backend/.env.dev

    volumes:
      - dev_pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-notesuser} -d ${POSTGRES_DB:-notesdb}"]
      interval: 5s
      timeout: 5s
      retries: 10

    labels:
      - "com.example.project=todo-notes"
      - "com.example.role=database"

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
      target: runtime

    env_file:
      - ../backend/.env.dev

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python -c \"import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/api/health/').status==200 else 1)\""
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

    labels:
      - "com.example.project=todo-notes"
      - "com.example.role=backend"


  frontend:

    image: node:20

    working_dir: /app

    volumes:
      - ../frontend:/app

    # Install deps, then run Vite dev server (exposes on 0.0.0.0 so host can reach it)
    command: bash -lc "npm ci && npm run dev -- --host"

    ports:
      - "5173:5173"

    labels:
      - "com.example.project=todo-notes"
      - "com.example.role=frontend"


volumes:

  dev_pgdata:
